// Copyright (c) 2017 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:projectid: jsf-container
:page-layout: guide
:page-duration: 10 minutes
:page-description: Learn how to get CDI integration when you bring your own JSF implementation using Open Liberty
:page-releasedate: 2018-01-06
:page-tags: ['JSF', 'Getting Started']
:page-permalink: /guides/{projectid}
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
:source-highlighter: prettify
= Bring your own JSF implementation to OpenLiberty

[.hidden]
NOTE: This repository contains the guide documentation source. To view the guide in published form, view it on the https://openliberty.io/guides/{projectid}.html[Open Liberty website].

Learn how to get CDI integration when you bring your own JSF implementation using Open Liberty

== What you'll learn

You will learn how to build a simple JSF application using the Mojarra JSF implementation packaged inside of the application.

Normally OpenLiberty uses an implementation of JSF called Apache MyFaces. If you want to use a different version of Apache MyFaces, or an entirely different JSF implementation such as Mojarra, you can follow this guide to find out how.

In this guide you will start off with a basic "hello world" JSF application that uses Mojarra.  Then, you will enable the JSF Container feature which will allow the application to make use of CDI integrations.

include::{common-includes}/gitclone.adoc[]

== What is JSF Container

TODO

== Starting up the basic JSF application

To start off there is a simple JSF application with one static page and one Java class to back it.

The index.xhtml file has some static text, and also displays the value of `#{JSFGreetingBean.greeting}`
[source]
----
include::finish/src/main/webapp/index.xhtml[]
----

The to evaluate the `#{JSFGreetingBean.greeting}` expression, the server looks for a bean named `JSFGreetingBean`, then invokes a `getGreeting()` method on it.  This will map to the JSFGreeingBean class in the application:
[source,java,indent=0]
----
include::start/src/main/java/io/openliberty/guides/jsfcontainer/JSFGreetingBean.java[]
----

One of the goals of this guide is to use Mojarra as the JSF implementation instead of the one that comes with OpenLiberty by default (Apache MyFaces).  To do this, a dependency is specified on Mojarra:
[source,groovy]
----
include::start/build.gradle[tag=dependencies]
----
By specifying the dependencies as type `compile`, the artifacts will be packaged into the war application under the `WEB-INF/lib/` directory, and therfore be on the application classpath at runtime.

Since the default JSF implementation is not being used, there is no JSF feature enabled in server.xml:
[source,xml,indent=0]
----
include::start/src/main/liberty/config/server.xml[]
----

To build and run this application, run the following command:
[source]
----
./gradlew libertyStart open
----

This will do the following things:
 1. Download and install liberty to the project build folder
 1. Compile and package the war application (including the index.xhtml file, JSFGreetingBean class, and Mojarra jars)
 1. Install the war application named `JSFContainerSample-1.0-SNAPSHOT` to the server
 1. Start the server

== Adding CDI to the JSF application

TODO

== Enable CDI integration using the JSF Container feature

TODO

== Great work! You're done!

You built and tested a web application project with an Open Liberty server using Gradle.

You can quickly create this project structure by using the https://liberty-app-accelerator.wasdev.developer.ibm.com/start/[Liberty App Accelerator] and choose to create a Gradle project.

include::{common-includes}/finish.adoc[]
